add_lunch_combo lineage_kminilte-eng
add_lunch_combo lineage_kminilte-user
add_lunch_combo lineage_kminilte-userdebug
add_lunch_combo omni_kminilte-eng
add_lunch_combo omni_kminilte-user
add_lunch_combo omni_kminilte-userdebug
